name: cube_off
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  awesome_bottom_bar: any
  dropdown_button2: ^2.3.9
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  flutter_js: ^0.7.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/scrambow.min.js
   - assets/scrambler.js